#!/bin/sh
set -eu

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)
SERVICE="$ROOT/packaging/systemd/openstock-daily-pipeline.service"
TIMER="$ROOT/packaging/systemd/openstock-daily-pipeline.timer"
PROVISIONER="$ROOT/packaging/systemd/openstock-provisioner.service"
CONTROL="$ROOT/packaging/deb/DEBIAN/control"
POSTINST="$ROOT/packaging/deb/DEBIAN/postinst"
PRERM="$ROOT/packaging/deb/DEBIAN/prerm"
POSTRM="$ROOT/packaging/deb/DEBIAN/postrm"
ARCHITECTURE="$ROOT/vnalpha/docs/11-deployment-architecture.md"
PROOF_REQUIREMENTS="$ROOT/vnalpha/docs/OPERATIONAL_PROOF_REQUIREMENTS.md"

systemd-analyze verify "$SERVICE" "$TIMER"
if [ -x /usr/bin/vnalpha ]; then
  systemd-analyze verify "$PROVISIONER"
fi
grep -Fx 'ExecStart=/usr/bin/flock -n -E 75 /run/openstock-pipeline.lock /usr/bin/vnalpha maintain enqueue --date today --json' "$SERVICE"
grep -Fx 'SuccessExitStatus=3' "$SERVICE"
grep -Fx 'OnCalendar=Mon..Fri *-*-* 17:30:00 Asia/Ho_Chi_Minh' "$TIMER"
grep -Fx 'Persistent=true' "$TIMER"
grep -Fx 'Unit=openstock-daily-pipeline.service' "$TIMER"
! grep -q '^\[Install\]' "$SERVICE"
! grep -q '^Requires=openstock-daily-pipeline.service' "$TIMER"
grep -q 'util-linux' "$CONTROL"
grep -q 'systemd' "$CONTROL"
grep -q 'tzdata' "$CONTROL"
test -f "$ROOT/packaging/deb/usr/lib/systemd/system/openstock-daily-pipeline.service"
test -f "$ROOT/packaging/deb/usr/lib/systemd/system/openstock-daily-pipeline.timer"
test -f "$ROOT/packaging/deb/usr/lib/systemd/system/openstock-provisioner.service"
cmp "$SERVICE" "$ROOT/packaging/deb/usr/lib/systemd/system/openstock-daily-pipeline.service"
cmp "$PROVISIONER" "$ROOT/packaging/deb/usr/lib/systemd/system/openstock-provisioner.service"
grep -Fx 'ExecStart=/usr/bin/flock -n /run/openstock-provisioner.lock /usr/bin/vnalpha provision worker --worker-id openstock-provisioner' "$PROVISIONER"
grep -Fx 'Environment=VNALPHA_PROVISIONING_QUEUE_PATH=/var/lib/openstock/queue/provisioning.sqlite3' "$PROVISIONER"
grep -Fx 'Restart=on-failure' "$PROVISIONER"
grep -Fx 'WantedBy=multi-user.target' "$PROVISIONER"
grep -q 'systemctl daemon-reload' "$POSTINST"
! grep -Eq 'systemctl (enable|start)|deb-systemd-helper enable' "$POSTINST"
grep -q 'systemctl stop openstock-daily-pipeline.service' "$PRERM"
grep -q 'systemctl stop openstock-provisioner.service' "$PRERM"
grep -q 'systemctl daemon-reload' "$POSTRM"
! grep -q 'rm -f.*LOCK_FILE' "$ROOT/packaging/scripts/openstock-run-pipeline"
grep -q 'VNALPHA_PROVISIONING_QUEUE_PATH' "$ARCHITECTURE"
grep -q 'openstock-provisioner.service' "$ARCHITECTURE"
! grep -q 'worker is not a daemon' "$ARCHITECTURE"
! grep -q 'vnalpha maintain daily' "$PROOF_REQUIREMENTS"
